### ISSUE TITLE
Lord protector's retainer breaks the game

### ISSUE THREAD

**Issue by Duckbringer** [throneteki-playtesting/throneteki#250]
Whenever conditions are satisfied to trigger lord protectors retainer, the game crashes.

**Comment by Duckbringer** [comment]
seems like a problem with GameActions.cancelEffects(context => ({ event: context.event })). this game action is only used in 2 other cards and those are from the bin pack, so probably wasn't tested much.

Implementation is also missing cost and message.

**Comment by Patane97** [comment]
@Duckbringer I think the issue is that the following `event.targets.hasSingleTarget()` and `event.targets.anySelection` needs to be `event.ability.targets`:
https://github.com/throneteki-playtesting/throneteki/blob/fcad4054dc80f53f1baf15a332f7c5f70df31eb2/server/game/cards/23-AHaH/LordProtectorsRetainer.js#L10-L16

**Comment by Duckbringer** [comment]
High Septon is implemented in similar way and has `event.targets.hasSingleTarget()` as well. I believe the problem was with the `event.ability.targets.some(target => target.type === 'choose')` as in ResolvedTargets.js `targetingType `is used, not just `type`


`
hasSingleTarget() {
        return this.selections.length === 1 && this.selections[0].targetingType === 'choose' && !Array.isArray(this.selections[0].value);
    }
`
